### ISSUE TITLE
Add jupyter-server-proxy tag to repo to facilitate discovery

### ISSUE THREAD

**Issue by riazarbi** [jupyterhub/jupyter-rsession-proxy#109]
### Proposed change
Add a tag `jupyter-server-proxy` to this github repo

### Alternative options
Do not add a tag `jupyter-server-proxy` to this github repo

### Who would use this feature?
People who search for software that make use of `jupyter-server-proxy` to spawn other IDEs from jupyterhub

### Rationale
The `jupyter-server-proxy` project recommends that software that make use of it add the above mentioned tag to their github repos to facilitate discovery. here - https://jupyter-server-proxy.readthedocs.io/en/latest/examples.html
  
The link https://github.com/topics/jupyter-server-proxy currently shows several other projects, but not this one. 

Why should you do this? The more people who find the package, the more people who use it, the more people who contribute to development.

**Comment by ryanlovett** [comment]
I've added the tag, thanks!
