### ISSUE TITLE
Bump version and document changes

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyter-rsession-proxy#111]
We should make a new release following the merge of #98 and #110. We can bump to version 1.5 ~~1.4, which is apropos since~~ -- we are now compatible with rstudio server 1.4 and their newer date-based versioning. ~~This is just a coincidence -- we don't set our version based on rstudio server's.~~

We now require jupyter-server-proxy 3.2.0.

Also notable is that we removed the check for the RSESSION_PROXY_RSTUDIO_1_4  environment variable. My feeling is that people who need rstudio server <= 1.3 (or one of the earlier 1.4 releases) can stay with jupyter-rsession-proxy 1.3.

My feeling is that it is sufficient to mention this in the README, but does anyone else feel otherwise?

Edit: we are already at version 1.4!

**Comment by ryanlovett** [comment]
Maybe this should be implemented in the form of a changelog, manually generated or otherwise.

**Comment by riazarbi** [comment]
Any objection to getting some CI going in GitHub actions? I often find that
a working Dockerfile is way more useful than a readme when trying to build
something.

I could try put something together and create an MR.

**Comment by ryanlovett** [comment]
@riazarbi Yes, it'd be great if you could add some automated testing in CI! Can you please create a new issue for that? If you'd like inspiration, jupyter-server-proxy [uses GitHub actions](https://github.com/jupyterhub/jupyter-server-proxy/blob/main/.github/workflows/test.yaml) to run [tests](https://github.com/jupyterhub/jupyter-server-proxy/tree/main/tests).

We used to include an example Dockerfile, but now reference rocker's binder docker image in the README. ([here](https://github.com/rocker-org/binder/blob/master/Dockerfile))

**Comment by ryanlovett** [comment]
Fixed by #112.
