### ISSUE TITLE
Example Dockerfile doesn't correctly configure/launch RStudio

### ISSUE THREAD

**Issue by Amir-Abushanab** [jupyterhub/jupyter-rsession-proxy#60]
## Expected behaviour:
RStudio launches and runs normally

## Actual behaviour:
RStudio fails to launch and keeps spitting out `ERROR R SUICIDE: unable to initialize the JIT` until it turns into a 500 error `could not start rstudio in time`

## Steps to reproduce:
Using the example Dockerfile and running 
`docker build . --tag=foo`
`docker run -p 8888:8888 -it foo:latest`

Haven't tested from other machines but I don't think that's the issue here. If anyone else has run into this/knows how to fix it please share! Thanks for your efforts!

**Comment by simis2626** [comment]
This problem was also reported in [#62](https://github.com/jupyterhub/jupyter-rsession-proxy/issues/62)

**Comment by ryanlovett** [comment]
We removed our Dockerfile in favor of rocker's, https://github.com/jupyterhub/jupyter-rsession-proxy/pull/82.
