### ISSUE TITLE
ERROR R SUICIDE: unable to initialize the JIT

### ISSUE THREAD

**Issue by alshabib** [jupyterhub/jupyter-rsession-proxy#62]
When launching the example container in a Jupyterhub environment we get the following error:

jupyter-adf30e4d811a54255caebaf68d0e1861.1.j71m99qdfki7    | 18 Feb 2019 16:39:53 [rsession-] ERROR R SUICIDE: unable to initialize the JIT
jupyter-adf30e4d811a54255caebaf68d0e1861.1.j71m99qdfki7    | ; LOGGED FROM: void {anonymous}::rSuicide(const string&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:2488

And a 500 error in the UI saying "could not start rstudio in time". 

Any idea what is happening here?

I am using the bleeding-edge jupyter-rsession-proxy. I tried 0.8.0 but then I no longer had the option for rstudio or rshiny.

Exec'ing into the container and running manually yields:
$ rsession --standalone=1 --program-mode=server --log-stderr=1 --session-timeout-minutes=0 --user-identity=jovyan --www-port=41109

18 Feb 2019 17:19:32 [rsession-] ERROR system error 2 (No such file or directory) [path=]; OCCURRED AT: rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) /home/ubuntu/rstudio/src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:3423

**Comment by simis2626** [comment]
I'm also having this same issue, but when trying to run the example container standalone on a docker host.
rsession-[142]: ERROR R SUICIDE: unable to initialize the JIT|||; LOGGED FROM: void {anonymous}::rSuicide(const string&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:2488
04 May 2019 06:47:02 [rsession-] ERROR R SUICIDE: unable to initialize the JIT

**Comment by FeatCrush** [comment]
Had the same issue. For me some r librairies installed with conda were in conflict with the installation of rstudio-server. To my knowledge the error "ERROR R SUICIDE: unable to initialize the JIT" is generic and the underneath error can be detected with the utility "rstudio-server verify-installation" directly in the container.

**Comment by scivm** [comment]
rstudio through rsession is giving me 500 also.  I am getting the dreaded linker error now also: rstudio-server verify-installation:
`/usr/lib/rstudio-server/bin/rsession: Relink `/opt/conda/lib/R/lib/../.././libgfortran.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'`

I temporarily gave up on this and started using the rocker tidyverse version as a base docker image and added Jupyter to it.  You cut and paste from base-notebook and then add 

`ENV LD_LIBRARY_PATH=/usr/local/lib/R/lib`

Working nicely

**Comment by ryanlovett** [comment]
Thanks @scivm. We'll just link to rocker's Dockerfile.
