### ISSUE TITLE
Could we make 'Shiny' menu item as optional?

### ISSUE THREAD

**Issue by standby7878** [jupyterhub/jupyter-rsession-proxy#70]
We do not need Shiny at our project at the moment. Could we somehow make 'Shiny' menu entry as optional?

**Comment by rmahajan2420** [comment]
We would like to remove the shiny from the drop down list as well. Any possibility ?

**Comment by scivm** [comment]
For me after installing rstudio into the docker kmage I see rstudio and shiny but the shiny gives a 500 error.  I want to remove as well.  Not sure yet where it comes from

**Comment by ryanlovett** [comment]
I think there's no reason why we shouldn't spin off the shiny bits into its own extension.
