### ISSUE TITLE
Disable Upload and Download functionality

### ISSUE THREAD

**Issue by rmahajan2420** [jupyterhub/jupyter-rsession-proxy#74]
Hi Everyone,

Really loving this. This really suits our use case to have rstudio running in container along with Jupyterhub, which has controls around. I need to ask one thing if it is possible to disable upload/download functionality from the Rstudio UI? Can't go with Enterprise version need to figure out any workaround for disabling those 2 functionality.

Thanks in Advance.

**Comment by yuvipanda** [comment]
Glad you like it, @rmahajan2420!

Unfortunately we don't have much control over what RStudio does, so we can't really add / remove functionality over what is possible in the open source version of RStudio. Maybe file a feature request in the RStudio git repoistory?

Hope this helps, and sorry that we can't help in this regard.
