### ISSUE TITLE
R Studio Initialization Error

### ISSUE THREAD

**Issue by mikeaadd** [jupyterhub/jupyter-rsession-proxy#80]
I've installed Jupyterhub, R server, and jupyter-rsession-proxy locally. I am able to select a RStudio kernel, however when I select It I get a "R Studio Initialization Error" as seen below. 

![Screen Shot 2020-02-17 at 4 08 03 PM](https://user-images.githubusercontent.com/12502807/74691507-4ad03e00-51a0-11ea-9cf6-aead5dc11f5f.png)

I've look through all the issues and have been unable to find a similar issue. I'm unsure on how to proceed. Does anyone have any insight on where I should investigate this issue?

**Comment by ryanlovett** [comment]
@mikeaadd I have seen this on the latest tagged release but it went away went I tried master, i.e. `pip install -U git+https://github.com/jupyterhub/jupyter-rsession-proxy`. Are you able to try the latest unreleased version?

**Comment by mikeaadd** [comment]
Thanks, that worked!

**Comment by ryanlovett** [comment]
Great, thanks!
